### PR TITLE
Better integration of AvNav in lysmarine/bbn

### PR DESCRIPTION
**Pull request by free-x**
Hi @mgrouch, @FredericGuilbault

here is PR that provides better integration of AvNav in your distribution

Regarding
free-x

### CODE REVIEW

**Comment by mgrouch** [comment]
Thanks. Merged

**Comment by mgrouch** [comment]
Thanks again for the patch.
I'm very close to the first release. 
I've build arm64 and armhf (32-bit) versions now. I've done some fair mount of testing on them.
32-bit one could be declared as a release.
64-bit is somewhat beta because raspberry pi foundation still doesn't consider it stable.
AvNav is included in the 'release' so please check it out.
Thanks again!

**Comment by FredericGuilbault** [comment]
@free-x  

What is the advantage to move files from `/var/lib/` to `/home/user` ?

From my perspective avnav is a web server and `/home/user` is a human user ( UID >= 1000 ).

**Comment by mgrouch** [comment]
While I took the pull request into my codebase to deliver something to users quickly I second Frederic concern. Server side stuff should run separately under different account from user UI.

**Pull request merged**
